# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/work/teamp1/teamp1.srcs/sources_1/bd/system/ip/system_tftlcd_0_0/system_tftlcd_0_0.xci
# IP: The module: 'system_tftlcd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/work/teamp1/teamp1.srcs/sources_1/bd/system/ip/system_tftlcd_0_0/src/blk_mem/blk_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem || ORIG_REF_NAME==blk_mem} -quiet] -quiet

# XDC: c:/work/teamp1/teamp1.srcs/sources_1/bd/system/ip/system_tftlcd_0_0/src/blk_mem/blk_mem_ooc.xdc

# IP: c:/work/teamp1/teamp1.srcs/sources_1/bd/system/ip/system_tftlcd_0_0/system_tftlcd_0_0.xci
# IP: The module: 'system_tftlcd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/work/teamp1/teamp1.srcs/sources_1/bd/system/ip/system_tftlcd_0_0/src/blk_mem/blk_mem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem || ORIG_REF_NAME==blk_mem} -quiet] -quiet

# XDC: c:/work/teamp1/teamp1.srcs/sources_1/bd/system/ip/system_tftlcd_0_0/src/blk_mem/blk_mem_ooc.xdc
